language: c
before_install:
  - "sudo apt-get update"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: sudo apt-get -q -y install intltool libgtk-3-dev
compiler:
  - gcc
  - clang
script: ./waf configure --prefix=/usr debug -j4
